services:

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./frontend/:/app/
    depends_on:
      - geoserver
      - database
    command: npm start
    networks:
      - dockernetw

  database:
    container_name: database
    build:
      context: ./database
      dockerfile: database.Dockerfile
    restart: always
    ports:
      - "5432:5432"
    networks:
      - dockernetw

  geoserver:
    container_name: geoserver
    build:
      context: ./geoserver
      dockerfile: geoserver.Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - dockernetw

#   util:
#     container_name: util
#     build:
#       context: ./util
#       dockerfile: util.Dockerfile
#     restart: no
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#     depends_on:
#       - geoserver
#     networks:
#       - dockernetw

networks:
  dockernetw:
    driver: bridge
